import { z } from "zod";

// Matches the placeholder images generated by src/lib/coverPlaceholder.ts
// (data:image/svg+xml;base64,...) so existing seeded posts stay editable.
// Restricted to image mime types to keep out data:text/html and similar.
const DATA_IMAGE_URI = /^data:image\/(png|jpe?g|gif|webp|svg\+xml);base64,[A-Za-z0-9+/]+=*$/i;

/**
 * Optional URL field: empty string is treated as "not provided" (-> undefined),
 * otherwise must be a valid http(s) URL or a data:image/... URI.
 */
const optionalUrl = z
  .string()
  .trim()
  .max(20000, "URL muito longa (máx. 20000 caracteres).")
  .optional()
  .or(z.literal(""))
  .transform((value) => (value ? value : undefined))
  .refine((value) => {
    if (value === undefined) return true;
    if (DATA_IMAGE_URI.test(value)) return true;
    if (!/^https?:\/\//i.test(value)) return false;
    try {
      new URL(value);
      return true;
    } catch {
      return false;
    }
  }, "URL inválida (use http://, https:// ou data:image/...).");

/**
 * Optional HTML datetime-local value ("YYYY-MM-DDTHH:mm"), used to schedule a
 * post's publishedAt. Empty string means "not provided" (-> undefined, which
 * falls back to "now" when the post is published).
 */
const optionalDateTimeLocal = z
  .string()
  .trim()
  .optional()
  .or(z.literal(""))
  .transform((value) => (value ? value : undefined))
  .refine((value) => value === undefined || !Number.isNaN(Date.parse(value)), "Data inválida.");

export const postSchema = z.object({
  title: z
    .string()
    .trim()
    .min(1, "Informe um título.")
    .max(200, "Título muito longo (máx. 200 caracteres)."),
  excerpt: z
    .string()
    .trim()
    .min(1, "Informe um resumo.")
    .max(500, "Resumo muito longo (máx. 500 caracteres)."),
  content: z
    .string()
    .trim()
    .min(1, "Informe o conteúdo.")
    // Content is JSON-encoded blocks (see src/lib/contentBlocks.ts) for posts
    // built with the block editor, so this needs more headroom than a plain
    // Markdown string would.
    .max(60000, "Conteúdo muito longo (máx. 60000 caracteres)."),
  coverImageUrl: optionalUrl,
  coverImageAlt: z
    .string()
    .trim()
    .max(300, "Texto alternativo muito longo (máx. 300 caracteres).")
    .optional()
    .or(z.literal(""))
    .transform((value) => (value ? value : undefined)),
  categoryId: z.string().trim().min(1, "Selecione uma categoria."),
  tagIds: z
    .array(z.string().trim().min(1))
    .max(20, "Selecione no máximo 20 tags.")
    .default([]),
  published: z.boolean(),
  publishedAt: optionalDateTimeLocal,
});

export const categorySchema = z.object({
  name: z
    .string()
    .trim()
    .min(1, "Informe um nome.")
    .max(100, "Nome muito longo (máx. 100 caracteres)."),
});

export const tagSchema = z.object({
  name: z
    .string()
    .trim()
    .min(1, "Informe um nome.")
    .max(50, "Nome muito longo (máx. 50 caracteres)."),
});

export const commentSchema = z.object({
  authorName: z
    .string()
    .trim()
    .min(1, "Informe seu nome.")
    .max(100, "Nome muito longo (máx. 100 caracteres)."),
  authorEmail: z
    .string()
    .trim()
    .max(200)
    .optional()
    .or(z.literal(""))
    .transform((value) => (value ? value : undefined))
    .refine(
      (value) => value === undefined || z.email().safeParse(value).success,
      "E-mail inválido.",
    ),
  body: z
    .string()
    .trim()
    .min(1, "Escreva um comentário.")
    .max(2000, "Comentário muito longo (máx. 2000 caracteres)."),
});

export const subscriberSchema = z.object({
  email: z.email("E-mail inválido.").trim().max(200),
});

export const siteSettingsSchema = z.object({
  siteName: z
    .string()
    .trim()
    .min(1, "Informe o nome do site.")
    .max(100, "Nome do site muito longo (máx. 100 caracteres)."),
  slogan: z
    .string()
    .trim()
    .min(1, "Informe o slogan.")
    .max(300, "Slogan muito longo (máx. 300 caracteres)."),
  logoUrl: optionalUrl,
  footerText: z
    .string()
    .trim()
    .min(1, "Informe o texto do rodapé.")
    .max(1000, "Texto do rodapé muito longo (máx. 1000 caracteres)."),
});

/** Returns the first Zod validation issue message, for simple single-line form errors. */
export function firstIssueMessage(error: z.ZodError): string {
  return error.issues[0]?.message ?? "Dados inválidos.";
}
