import { z } from "zod";

// Matches the placeholder images generated by src/lib/coverPlaceholder.ts
// (data:image/svg+xml;base64,...) so existing seeded posts stay editable.
// Restricted to image mime types to keep out data:text/html and similar.
const DATA_IMAGE_URI = /^data:image\/(png|jpe?g|gif|webp|svg\+xml);base64,[A-Za-z0-9+/]+=*$/i;

/**
 * Optional URL field: empty string is treated as "not provided" (-> undefined),
 * otherwise must be a valid http(s) URL or a data:image/... URI.
 */
const optionalUrl = z
  .string()
  .trim()
  .max(20000, "URL muito longa (máx. 20000 caracteres).")
  .optional()
  .or(z.literal(""))
  .transform((value) => (value ? value : undefined))
  .refine((value) => {
    if (value === undefined) return true;
    if (DATA_IMAGE_URI.test(value)) return true;
    if (!/^https?:\/\//i.test(value)) return false;
    try {
      new URL(value);
      return true;
    } catch {
      return false;
    }
  }, "URL inválida (use http://, https:// ou data:image/...).");

export const postSchema = z.object({
  title: z
    .string()
    .trim()
    .min(1, "Informe um título.")
    .max(200, "Título muito longo (máx. 200 caracteres)."),
  excerpt: z
    .string()
    .trim()
    .min(1, "Informe um resumo.")
    .max(500, "Resumo muito longo (máx. 500 caracteres)."),
  content: z
    .string()
    .trim()
    .min(1, "Informe o conteúdo.")
    .max(20000, "Conteúdo muito longo (máx. 20000 caracteres)."),
  coverImageUrl: optionalUrl,
  categoryId: z.string().trim().min(1, "Selecione uma categoria."),
  published: z.boolean(),
});

export const categorySchema = z.object({
  name: z
    .string()
    .trim()
    .min(1, "Informe um nome.")
    .max(100, "Nome muito longo (máx. 100 caracteres)."),
});

export const siteSettingsSchema = z.object({
  siteName: z
    .string()
    .trim()
    .min(1, "Informe o nome do site.")
    .max(100, "Nome do site muito longo (máx. 100 caracteres)."),
  slogan: z
    .string()
    .trim()
    .min(1, "Informe o slogan.")
    .max(300, "Slogan muito longo (máx. 300 caracteres)."),
  logoUrl: optionalUrl,
  footerText: z
    .string()
    .trim()
    .min(1, "Informe o texto do rodapé.")
    .max(1000, "Texto do rodapé muito longo (máx. 1000 caracteres)."),
});

/** Returns the first Zod validation issue message, for simple single-line form errors. */
export function firstIssueMessage(error: z.ZodError): string {
  return error.issues[0]?.message ?? "Dados inválidos.";
}
